#!/bin/bash
#PBS -N build.index
#PBS -l nodes=1:ppn=32
#PBS -l walltime=2400:00:00
#PBS -q cu-2
#PBS -V
#PBS -S /bin/bash
## I can use cu-2 and fat-2

#NP=`cat $PBS_NODEFILE | wc -l`
#NN=`cat $PBS_NODEFILE | sort | uniq | tee /tmp/nodes.$$ | wc -l`
#cat "$PBS_NODEFILE" | uniq  > /tmp/nodefile.$$

cd $PBS_O_WORKDIR
#module load XXX

# echo job run node list
#echo "PBS nodefile:"
#echo "++++++++++++++++++++++++++++++++++++"
#cat $PBS_NODEFILE
#echo "++++++++++++++++++++++++++++++++++++"

sh build.index.sh ~/Genomes/hg19/hg19.fa.bz2 hg19.refGene.txt.gz hg19

#echo "Program Finished at "`date`
#echo "Removing scratch files ...."
rm -rf /tmp/nodefile.$$
rm -rf /tmp/nodes.$$

